# action.yml
name: 'Swagger Codegen CLI v3'
description: 'Run Swagger Codegen CLI v3 in Github Actions'
branding:
    icon: code
    color: green
runs:
  using: 'docker'
  image: 'docker://swaggerapi/swagger-codegen-cli-v3'
